### ISSUE TITLE
Minecraft Version

### ISSUE THREAD

**Issue by ITCMD** [johnsusek/mverse#1]
Nowhere on this github does it say which minecraft versions this mod if compatible with. I'd love to use it for my 1.16.4 server.

**Comment by johnsusek** [comment]
Hi, thanks for checking out this project! I haven't really touched it since the initial creation, but excited for anyone to pick it up and run with it.

The docs here: 
https://github.com/johnsusek/mverse/tree/master/server

use version 1.15.2-31.2.27

If it doesn't work with recent versions, it might be best to use the version from the docs and then step forward minor versions to see if anything breaks
